### ISSUE TITLE
Improve layout of Working Sessions pages

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#162]
![image](https://user-images.githubusercontent.com/656739/38361396-19d9d130-38c5-11e8-9efa-ce4f0b0866d3.png)

Do something like we did for the PBX GS site

![image](https://user-images.githubusercontent.com/656739/38361418-2b2149f0-38c5-11e8-9127-b52b4eb69983.png)

**Comment by fzipi** [comment]
@Lisa-devseccon This was part of what Jonathon was doing, right?

**Comment by sarahallencruz** [comment]
New Layout for working session page. To be merged with Jonathon's top banner design,
<img width="1257" alt="screen shot 2018-05-01 at 17 09 45" src="https://user-images.githubusercontent.com/38696765/39664498-ba818038-507b-11e8-9127-f69e173c1e6c.png">

**Comment by VasBu** [comment]
Hi @sarahallencruz,

Thank you very much for sharing this information. I think that this one is related to one of the items in the checklist under #244 . So, thanks a lot for providing this one.
I'll continue with the comments under @244 and I'll tag your name under that issue.

**Comment by VasBu** [comment]
@sarahallencruz, would you please confirm that this issue is closed meaning that you do not plan to have any additional activities in a context of designing he layout for the "working sessions" page?

I'm trying to keep GitHub issues and project in a healthy condition. In that context if you do not plan any additional activities here, I would close this issue. 
BTW information about the new layout posed under this issue is already proceed to @fzipi and he can implement the details from the new layout. (please see the latest comments under #244 )
