### ISSUE TITLE
Problems with menu in venue page

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#265]
Check https://open-security-summit.org/venue/#

**Comment by fzipi** [comment]
@JemmaDSmith Can't reproduce the problem, the menu is still there. Could you attach a screenshot please?

**Comment by fzipi** [comment]
Close. Can't reproduce.

**Comment by VasBu** [comment]
@fzipi , Let me try to provide some information here. I just tested quickly and yes, the menu is there but the problem is that the sub-menus that has to be displayed on click on "About" and "Sessions" are not showing. 

You see.. I just clicked and the dropdown menu is missing.

![image](https://user-images.githubusercontent.com/15072044/39529115-34b095b8-4e26-11e8-9d43-8755212df7a9.png)
