### ISSUE TITLE
Create page that explains the differences between a Working Session and User Session

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#286]
![image](https://user-images.githubusercontent.com/656739/39306373-f122082c-4957-11e8-8f8f-b57124f6e2c3.png)

I would say it more like

**Working Sessions** - work on specific topics
**User Sessions** - hands on session on specific topic (avoid presentations and one-to-many environments)

**Comment by sarahallencruz** [comment]
See images on #363

**Comment by fionarichmond** [comment]
Would this sit best in FAQs? I can write some copy this afternoon

**Comment by fionarichmond** [comment]
Thanks @VasBu 
Suggested copy:
Q. What is the difference between a Working Session and a User session
Working Sessions focus on creating and evolving ideas, in order to create outcomes that will have an impact in the real world. They are a great way to join a group of practitioners to share expertise and knowledge on a particular subject.
<visual>
User sessions are much more practical sessions, which will enable you to learn new skills or develop existing ones. They are also an opportunity to test out the outcomes of some of the Working Sessions. These are a presentation-free environment, driven by practitioners working with users.
<visual>

**Comment by VasBu** [comment]
@fionarichmond , Maybe @DinisCruz or/and Francois Raynaud will be much more competent than my, but in the name of moving the things forward a bit more faster, I would like to share my opinion which is:

I think that it's good, especially for the first version.

**Comment by sarahallencruz** [comment]
Hi All, I've also done a schematic of the difference between working and user sessions, perhaps they can be inserted as well, Sarah
<img width="1410" alt="user session wordbubbles" src="https://user-images.githubusercontent.com/38696765/39926824-4f5f745c-5528-11e8-9db4-3f148e236a14.png">
<img width="1351" alt="working session wordbubbles" src="https://user-images.githubusercontent.com/38696765/39926825-4f7b0c3a-5528-11e8-9989-500a8c24f3a1.png">
<img width="839" alt="user session icon" src="https://user-images.githubusercontent.com/38696765/39926847-602c6114-5528-11e8-8c63-57167430ac75.png">
<img width="939" alt="working sessions icon" src="https://user-images.githubusercontent.com/38696765/39926848-6049858c-5528-11e8-95b3-58b56086518f.png">
<img width="771" alt="attendees roles icon" src="https://user-images.githubusercontent.com/38696765/39926849-6066130a-5528-11e8-8549-058b4a554667.png">

**Comment by fionarichmond** [comment]
Hi @sarahallencruz yes, absolutely, I suggested using the Working and User Sessions for the FAQ about this, as that might help people see the difference

**Comment by VasBu** [comment]
I'll try to create a new FAQ page with the provided content and illustrations
