### ISSUE TITLE
Outcomes Buttons on Session Pages

### ISSUE THREAD

**Issue by almeidam** [OpenSecuritySummit/oss2018#563]
https://owasp.slack.com/files/UA7P8E2DB/FAUPG0NJZ/image.png

1. @fzipitria can we implement this 2018 outcomes with two states and the previous outcomes pointing to one url.

2. I have created the following  in local  admin to get a birds eye view of the outcomes also for promo.

**Comment by fzipi** [comment]
@almeidam What URL will these buttons point to? `outcomes:` for example?
Should we use as a convention to name the outcomes to the same filename of the sessions, so pointing to them will be automatic? E.g: `outcomes: {{ ref "outcomes/... }}`

**Comment by VasBu** [comment]
@almeidam , @fzipi ,

Would you please confirm that this issue is in a line with #288 ?
The mentioned GitHub issue can really bring great value to persons who are interested in a topic making a chain between the two sessions on two summits by referencing from a session in the summit 2018 to the outcome from a session in the summit 2017.

@almeidam , would you please confirm that your idea related to this issue is:

**to have a link from a session 2018 page to the outcome 2017 page?**

I had quick chat with @devseccon today. He mentioned that he is writing an blog post that he would like to promote on Monday (28/05/2018) which I guess making an accent of the importance of outcomes from 2017 and the follow up that has to happen for some of the sessions in the following summit.
It sounds important we have those relations.

@almeidam , @fzipi I would be glad to help about this one. Just let's agree how we can implement this one. I would try to identify the necessary activities that has to be taken, at least by my opinion.

- [ ] Do mapping between current sessions from 2018 and outcomes from 2017
- [ ] Decision about how we implement this one? (**note:** will need to have specific link to an outcome from 2017. I think that clue buttons will not work for us about this one)
- [ ] Implement the changes (I would be glad to help here. If all three of us can work on this one, we might be finished in a record time)

Thoughts?

**Comment by fzipi** [comment]
@VasBu I think a simple imprementation of this would be:
- add a new parameter to front matter, called `outcomes_2017'
You can see an example [here](https://github.com/OpenSecuritySummit/oss2018/blob/master/content/tracks/DevSecOps/working-sessions/securing-github-integrations.md).
Just put there the full link to the corresponding outcome.
- I will add the changes with the buttons.

**Comment by almeidam** [comment]
@VasBu this request will handle that and the new outcomes of 2018. The outcomes 2018 button to go to individual outcomes whereas the Previous outcomes buttom to go to the 2017 outcomes page.

**Comment by fzipi** [comment]
I´ve added the new fields `outcomes:` and `outcomes_2017:` for tracking them. Now we only need to generate the outcomes and do the mapping.

**Comment by fzipi** [comment]
This was merged today.
